// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRL0ocfan4fhskdldjic92QkZMnQrcG_o',
    appId: '1:726996368880:web:52fcc27fd254acb6057135',
    messagingSenderId: '726996368880',
    projectId: 'formfit-ai-84d42',
    authDomain: 'formfit-ai-84d42.firebaseapp.com',
    storageBucket: 'formfit-ai-84d42.firebasestorage.app',
    measurementId: 'G-MYJWDMST8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzvX_8OvGlGOM35uwwUX9Tkbxj5knlSIU',
    appId: '1:726996368880:android:2b5fa1837e60f237057135',
    messagingSenderId: '726996368880',
    projectId: 'formfit-ai-84d42',
    storageBucket: 'formfit-ai-84d42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqrWo8QHC63XceypQhQW3IwD5_t15bVRQ',
    appId: '1:726996368880:ios:b40f0c5983b952da057135',
    messagingSenderId: '726996368880',
    projectId: 'formfit-ai-84d42',
    storageBucket: 'formfit-ai-84d42.firebasestorage.app',
    iosBundleId: 'com.example.formfitAi',
  );
}
